name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_open_street_map: ^0.0.3
  flutter_map: ^1.0.0
  location: ^4.4.0
  geolocator: ^7.6.2
  lite_rolling_switch: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  custom_map_markers: ^0.0.1
  flutter_osm_plugin: ^0.53.4+1
  vector_map_tiles: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets : 
  - assets/arrow.png

flutter_icons:
  image_path: "assets/logo.png"
  map_path: "assets/map_openstreet.osm"
  android: true
  ios: true
