name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^1.0.0
  udp: ^5.0.3
  mapbox_gl: ^0.14.0-nullsafety.0
  flutter_native_splash: ^2.0.2
  cached_network_image: ^3.2.0
  location: ^4.2.0
  geolocator: ^9.0.2
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
  - assets/arrow.png

flutter_icons:
  image_path: "assets/logo.png"
  map_path: "assets/map_openstreet.osm"
  android: true
  ios: true
